---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    
- name: tasks for RedOS7.1-2
  block:

    - name: copy /etc/yum.repos.d/nginx.repo (RedOS7.2)
      ansible.builtin.copy:
        src: yum.repos.d/nginx.repo7
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['distribution_version'] == "7.2"

    - name: python2-supported task
      block: 

        - name: install ca-certificates (RedOS7.1-2)
          yum:
            name: ca-certificates

        - name: install nginx (RedOS7.1-2)
          yum:
            name: nginx

      vars:
        ansible_python_interpreter: /usr/bin/python2

  when: ansible_facts['distribution_version'] == "7.2" or 
        ansible_facts['distribution_version'] == "7.1"

- name: tasks for RedOS7.3
  block:

    - name: copy /etc/yum.repos.d/nginx.repo (RedOS7.3)
      ansible.builtin.copy:
        src: yum.repos.d/nginx.repo8
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: '0644'

    - name: install nginx (RedOS7.3)
      yum:
        name: nginx

  when: "'7.3' in ansible_facts['distribution_version']"

- name: copy /etc/nginx/nginx.conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: copy /etc/nginx/conf.d/r7-office.conf
  ansible.builtin.template:
    src: conf.d/r7-office.conf.j2
    dest: /etc/nginx/conf.d/r7-office.conf
    owner: root
    group: root
    mode: '0644'

- name: remove /etc/nginx/conf.d/default.conf
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: create a directory /etc/nginx/ssl
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: copy crt 
  ansible.builtin.copy:
    src: ssl/domain.crt
    dest: /etc/nginx/ssl/domain.crt
    owner: root
    group: root
    mode: '0644'

- name: copy key
  ansible.builtin.copy:
    src: ssl/domain.key
    dest: /etc/nginx/ssl/domain.key
    owner: root
    group: root
    mode: '0644'

- name: started nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
    