-- specific translations
UPDATE res_data SET textValue='Количество пользователей' WHERE fileid=29 AND title='CompanySizeTitle' AND cultureTitle='ru';
UPDATE res_data SET textValue='h1.Запрос тарифа для SAAS-портала "${__VirtualRootPath}":"${__VirtualRootPath}"\n\nh3.Имя\n$UserName\n\nh3.Фамилия\n$UserLastName\n\nh3.Email\n"$UserEmail":"mailto:$UserEmail"\n\nh3.Телефон\n$Phone\n\nh3.Название компании\n$CompanyTitle\n\nh3.Количество пользователей\n$CompanySize' WHERE fileid=250 AND title='pattern_request_tariff1' AND cultureTitle='ru';

-- remove redundant translations
DELETE FROM res_data WHERE cultureTitle NOT IN ('Neutral', 'ru');

-- replace product link\text
UPDATE res_data SET textValue=REPLACE(textValue, 'onlyoffice.com', 'r7-office.ru');
UPDATE res_data SET textValue=REPLACE(textValue, 'ONLYOFFICE™', 'ONLYOFFICE');
UPDATE res_data SET textValue=REPLACE(textValue, 'ONLYOFFICE', 'R7-OFFICE');
UPDATE res_data SET textValue=REPLACE(textValue, 'R7-OFFICE', 'Р7-Офис') WHERE cultureTitle='ru';

-- empty social networks icons
UPDATE res_data SET textValue='' WHERE title='SocialNetworksFooterV10';

-- update activation\welcome mails
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nВы только что создали портал Р7-Офис, виртуальный офис вашей команды для эффективной совместной работы. Его адрес - "${__VirtualRootPath}":"${__VirtualRootPath}". \n\nПожалуйста, подтвердите ваш e-mail: \n\n$GreenButton\n\nСсылка действительна в течение 7 дней.\n\nВсегда Ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_activation_v10';

UPDATE res_data SET textValue='Настройте ваш Р7-Офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_welcome_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nCustomize and manage your R7-OFFICE to make it more comfortable and secure:\n\n$TableItemsTop $TableItem1 $TableItem2 $TableItem3 $TableItem4 $TableItem5 $TableItem6 $TableItemsBtm\n\nAnd that’s not the full list of what you can do! \n\n$GreenButton\n   \nVisit our "Help Center":"${__HelpLink}" to learn more about customizing your office. Always consult it when you have questions about the functionality and encourage your users to do so.\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_welcome_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nНастройте и администрируйте ваш Р7-Офис для удобной и безопасной работы:\n\n$TableItemsTop $TableItem1 $TableItem2 $TableItem3 $TableItem4 $TableItem5 $TableItem6 $TableItemsBtm\n\nИ это далеко не полный список того, что вы можете!\n\n$GreenButton\n   \nПосетите наш "Справочный центр":"${__HelpLink}", чтобы узнать больше о настройке вашего офиса. Он всегда поможет вам и вашим пользователям сориентироваться в функциональности портала.\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_welcome_v10';

UPDATE res_data SET textValue='Приглашение ${__VirtualRootPath}' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_user_activation_v10';
UPDATE res_data SET textValue='Здравствуйте!\n\nВы приглашены на портал "${__VirtualRootPath}":"${__VirtualRootPath}". Примите приглашение, нажав на ссылку:\n\n$GreenButton\n\nМы будем время от времени отправлять вам полезные советы, последние новости Р7-Офис и специальные предложения. Вы можете отменить подписки на странице своего профиля в любой момент, а также заново подключить их.\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_user_activation_v10';

UPDATE res_data SET textValue='Добро пожаловать в ваш Р7-Офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_user_welcome_v10';
UPDATE res_data SET textValue='Hello!\n\nWelcome to R7-OFFICE! Your user profile has been successfully added to the portal at "${__VirtualRootPath}":"${__VirtualRootPath}". Now you can:\n\n# Create and edit "Documents":"${__VirtualRootPath}/products/files/", share them with teammates, and collaborate in real time.\n# Add your email accounts and manage all correspondence in one place with "Mail":"${__VirtualRootPath}/addons/mail/".\n# Manage your workflow with "Projects":"${__VirtualRootPath}/products/projects/" and your customer relationships using "CRM":"${__VirtualRootPath}/products/crm/".\n# Use "Community":"${__VirtualRootPath}/products/community/" to start your blogs, forums, add events, share bookmarks.\n# Organize your work schedule with the built-in "Calendar":"${__VirtualRootPath}/addons/calendar/".\n# Use "Chat":"${__VirtualRootPath}/addons/talk/" to exchange instant messages.\n\n$GreenButton\n\nIf you need help, browse our "Help Center":"${__HelpLink}" or ask our "support team":"https://r7-office.zendesk.com/hc/ru/requests/new".\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_user_welcome_v10';
UPDATE res_data SET textValue='Здравствуйте!\n\nДобро пожаловать в Р7-Офис! Ваш пользовательский профиль успешно добавлен на портал "${__VirtualRootPath}":"${__VirtualRootPath}". Теперь вы можете:\n\n# Создавать и редактировать "документы":"${__VirtualRootPath}/products/files/", делиться ими с участниками команды и вести совместную работу в режиме реального времени.\n# Добавить свою учетную запись электронной почты и централизованно управлять всей корреспонденцией в модуле "Почта":"${__VirtualRootPath}/addons/mail/".\n# Управлять рабочим процессом с помощью модуля "Проекты":"${__VirtualRootPath}/products/projects/" и взаимоотношениями с клиентами, используя модуль "CRM":"${__VirtualRootPath}/products/crm/".\n# Использовать "Сообщество":"${__VirtualRootPath}/products/community/", чтобы вести блоги, общаться на форумах, добавлять события, делиться закладками.\n# Планировать свой график с помощью встроенного "Календаря":"${__VirtualRootPath}/addons/calendar/".\n# Использовать "Чат":"${__VirtualRootPath}/addons/talk/" для обмена мгновенным сообщениями.\n\n$GreenButton\n\nЕсли вам требуется помощь, посетите наш "Справочный центр":"${__HelpLink}" или обратитесь в нашу "службу поддержки":"https://r7-office.zendesk.com/hc/ru/requests/new".\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_user_welcome_v10';

UPDATE res_data SET textValue='Приглашение в ${__VirtualRootPath}' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_guest_activation_v10';
UPDATE res_data SET textValue='Здравствуйте!\n\nВы приглашены на портал "${__VirtualRootPath}":"${__VirtualRootPath}" в качестве гостя. Примите приглашение, нажав на ссылку:\n\n$GreenButton\n\nМы будем время от времени отправлять вам полезные советы, последние новости Р7-Офис и специальные предложения. Вы можете отменить подписки на странице своего профиля в любой момент, а также заново подключить их.\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_guest_activation_v10';

UPDATE res_data SET textValue='Hello!\n\nYour guest profile has been successfully added to "${__VirtualRootPath}":"${__VirtualRootPath}".  Now you can:\n\n# Edit your "profile":"$MyStaffLink".\n# View and comment the content available in the "Community":"${__VirtualRootPath}/products/community/" and "Projects":"${__VirtualRootPath}/products/projects/".\n# Add and download files available for you in the "Documents":"${__VirtualRootPath}/products/files/".\n# Organize your schedule with the built-in "Calendar":"${__VirtualRootPath}/addons/calendar/".\n# Use "Chat":"${__VirtualRootPath}/addons/talk/" to exchange instant messages.\n\n$GreenButton\n\nIf you need help, browse our "Help Center":"${__HelpLink}" or ask our "support team":"https://r7-office.zendesk.com/hc/ru/requests/new".\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_guest_welcome_v10';
UPDATE res_data SET textValue='Здравствуйте!\n\nВаш гостевой профиль был успешно добавлен к "${__VirtualRootPath}":"${__VirtualRootPath}". Теперь вы можете:\n\n# Редактировать свой "профиль":"$MyStaffLink".\n# Просматривать и комментировать контент, доступный в "Сообществе":"${__VirtualRootPath}/products/community/" и "Проектах":"${__VirtualRootPath}/products/projects/".\n# Добавлять и скачивать файлы, доступные для вас в модуле "Документах":"${__VirtualRootPath}/products/files/".\n# Организовывать свое расписание с помощью встроенного "Календаря":"${__VirtualRootPath}/addons/calendar/".\n# Использовать "Чат":"${__VirtualRootPath}/addons/talk/" для обмена мгновенным сообщениями.\n\n$GreenButton\n\nЕсли вам требуется помощь, посетите наш "Справочный центр":"${__HelpLink}" или обратитесь в нашу "службу поддержки":"https://r7-office.zendesk.com/hc/ru/requests/new".\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_guest_welcome_v10';

-- update periodic mails
UPDATE res_data SET textValue='Пригласите коллег в ваш облачный офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_invite_teammates_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nThe cloud office is ready at "${__VirtualRootPath}":"${__VirtualRootPath}". It’s time to invite your teammates! \n\nThe easiest way to do that is to distribute the invitation link using the *Invite users to portal* option.\n\n$GreenButton\n\nYou can also add your teammates manually one by one using the *Create New...* button in the *People* module or export users from:\n    "your mail client address book":"${__HelpLink}/administratorguides/import-contacts-from-mail-client.aspx",\n    "a CSV file":"${__HelpLink}/administratorguides/import-contacts-from-csv.aspx". \n\nLearn more about adding users in our "Help Center":"${__HelpLink}".\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_invite_teammates_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nОблачный офис готов к работе по адресу "${__VirtualRootPath}":"${__VirtualRootPath}". Самое время пригласить ваших коллег!\n\nСамый простой способ сделать это - разослать ссылку приглашения, используя опцию *Пригласить пользователей на портал*.\n\n$GreenButton\n\nВы также можете добавить своих коллег по одному с помощью кнопки *Создать...* в модуле *Люди* или экспортировать пользователей из:\n    "адресной книги почтового клиента":"${__HelpLink}/administratorguides/import-contacts-from-mail-client.aspx",\n    "файла CSV":"${__HelpLink}/administratorguides/import-contacts-from-csv.aspx". \n\nУзнайте больше о добавлении пользователей в нашем "Справочном центре":"${__HelpLink}".\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_invite_teammates_v10';

UPDATE res_data SET textValue='Лучшие практики от команды Р7-Офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_without_activity_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nWe hope you enjoy using R7-OFFICE and we would really appreciate you feedback!. Contact us at "https://r7-office.zendesk.com/hc/ru/requests/new":"https://r7-office.zendesk.com/hc/ru/requests/new" whenever you have any questions/ ideas.\n\nSome tips from team:\nWatch our free webinars to learn more about R7-OFFICE.\nSwitch to free "R7-OFFICE Personal":"https://test-cloud.r7-office.ru/" if don’t have any teammates and only want to store and edit your docs.\n"Download R7-OFFICE Desktop Editors":"https://r7-office.ru/request_redactor" if you want an alternative to MS Office.\nGet free R7-OFFICE for iOS and Android to work on docs from your mobile device.\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_without_activity_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nМы надеемся, что вам нравится работать с Р7-Офис, и мы будем очень благодарны вам за ваши отзывы! Напишите нам на "https://r7-office.zendesk.com/hc/ru/requests/new":"https://r7-office.zendesk.com/hc/ru/requests/new", когда у вас есть какие-либо вопросы / идеи.\n\nНесколько советов от нашей команды:\nСмотрите наши бесплатные вебинары, чтобы узнать больше об Р7-Офис.\nПереключитесь на бесплатную версию Р7-Офис "Персональное облако":"https://test-cloud.r7-office.ru/", если у вас нет товарищей по команде, и вы хотите только сохранять и редактировать свои документы.\n"Скачайте Р7-Офис Редакторы":"https://r7-office.ru/request_redactor", если вы хотите альтернативу MS Office.\nПолучите бесплатные приложения Р7-Офис для iOS и Android для работы с документами с вашего мобильного устройства.\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_without_activity_v10';

UPDATE res_data SET textValue='7 секретов эффективной работы с документами' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_user_docs_tips_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nWe hope you enjoy using R7-OFFICE editors. Here are some tips on how to make it more effective.\n\n$TableItemsTop $TableItem1 $TableItem2 $TableItem3 $TableItem4 $TableItem5 $TableItem6 $TableItem7 $TableItemsBtm\n\n$GreenButton\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_docs_tips_v10';
UPDATE res_data SET textValue='R7-OFFICE provides you with the most complete set of styling and formatting tools. <a target="_blank" href="https://helpcenter.r7-office.ru/documentation-editors/description-document-Editor/UsageInstructions/FormattingPresets.aspx">Learn more</a>' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_docs_tips_v10_item_formatting';
UPDATE res_data SET textValue='While co-editing a doc with your team in real time, switch to <a target="_blank" href="https://helpcenter.r7-office.ru/documentation-editors/description-document-Editor/HelpfulHints/CollaborativeEditing.aspx">Fast mode</a> to see changes as your co-author is typing or to <a target="_blank" href="https://helpcenter.r7-office.ru/documentation-editors/description-document-Editor/HelpfulHints/CollaborativeEditing.aspx">Strict mode</a> to get more privacy.' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_docs_tips_v10_item_coediting';
UPDATE res_data SET textValue='Connect Yandex.Disk or other services to manage your files in one place.' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_docs_tips_v10_item_3rdparty';
UPDATE res_data SET textValue='Download the apps to work on docs <a target="_blank" href="https://r7-office.ru/request_redactor">offline</a> as well as on <a target="_blank" href="https://apps.apple.com/ru/app/%D1%807-%D0%BE%D1%84%D0%B8%D1%81-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/id1451950062">iOS</a> and <a target="_blank" href="https://play.google.com/store/apps/details?id=ru.nct.documents&hl=ru">Android</a> devices.' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_docs_tips_v10_item_apps';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nНадеемся, вам нравится работать с редакторами Р7-Офис. Вот несколько советов, чтобы сделать вашу работу эффективнее:\n\n$TableItemsTop $TableItem1 $TableItem2 $TableItem3 $TableItem4 $TableItem5 $TableItem6 $TableItem7 $TableItemsBtm\n\n$GreenButton\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10';
UPDATE res_data SET textValue='Попробуйте расширенные возможности форматирования' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_formatting_hdr';
UPDATE res_data SET textValue='Р7-Офис предоставляет вам наиболее полный набор инструментов для управления стилями и форматирования. <a target="_blank" href="https://helpcenter.r7-office.ru/documentation-editors/description-document-Editor/UsageInstructions/FormattingPresets.aspx">Узнать больше</a>:' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_formatting';
UPDATE res_data SET textValue='Совместно работайте с документами' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_share_hdr';
UPDATE res_data SET textValue='Предоставляйте доступ к вашим документам для совместной работы вашим коллегам или группам пользователей. Определяйте различные уровни доступа - Только чтение, Комментирование, Заполнение полей форм, Только просмотр или Полный доступ.' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_share';
UPDATE res_data SET textValue='Выберите режим совместного редактирования' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_coediting_hdr';
UPDATE res_data SET textValue='При совместном редактировании документа членами вашей команды в режиме реального времени переключитесь в <a target="_blank" href="https://helpcenter.r7-office.ru/documentation-editors/description-document-Editor/HelpfulHints/CollaborativeEditing.aspx">Быстрый режим</a>, чтобы видеть изменения по мере того, как ваш соавтор печатает, или в <a target="_blank" href="https://helpcenter.r7-office.ru/documentation-editors/description-document-Editor/HelpfulHints/CollaborativeEditing.aspx">Строгий режим</a>, для большей конфиденциальности.' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_coediting';
UPDATE res_data SET textValue='Рецензируйте, комментируйте и обменивайтесь сообщениями' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_review_hdr';
UPDATE res_data SET textValue='Используйте Рецензирование, чтобы предлагать изменения без внесения исправлений в исходный документ, добавляйте комментарии, чтобы поделиться своими мыслями по конкретному фрагменту, или общайтесь не выходя из документа с помощью мгновенных сообщений.' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_review';
UPDATE res_data SET textValue='Подключайте сторонние облачные хранилища' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_3rdparty_hdr';
UPDATE res_data SET textValue='Подключите Яндекс.Диск или другие сервисы, чтобы управлять своими файлами в одном месте.' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_3rdparty';
UPDATE res_data SET textValue='Прикрепляйте документы к проектам и электронным письмам' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_attach_hdr';
UPDATE res_data SET textValue='Хранилище документов интегрировано со всеми модулями Р7-Офис, так что вы забудете и постоянных загрузках, и выгрузках документы в почте, СРМ и других ваших офисных программах.' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_attach';
UPDATE res_data SET textValue='Используйте приложения' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_apps_hdr';
UPDATE res_data SET textValue='Загружайте приложения Р7-Офис для работы в <a target="_blank" href="https://r7-office.ru/request_redactor">автономном режиме</a> на компьютере, а также на устройствах <a target="_blank" href="https://apps.apple.com/ru/app/%D1%807-%D0%BE%D1%84%D0%B8%D1%81-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/id1451950062">iOS</a> и <a target="_blank" href="https://play.google.com/store/apps/details?id=ru.nct.documents&hl=ru">Android</a>.' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_docs_tips_v10_item_apps';

UPDATE res_data SET textValue='Секреты комфортной работы' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_user_comfort_tips_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nWe have prepared several tips to make your work with R7-OFFICE more comfortable\n\n*#1 Find quick answers about R7-OFFICE functionality*\n\nBrowse "Help Center":"${__HelpLink}" when you are not sure how to perform your task. The answers to the most popular question like "how to import contacts to CRM":"${__HelpLink}/guides/import-contacts.aspx" or "how to export data from CRM":"${__HelpLink}/guides/export-data.aspx", or "how to add a recurring event":"${__HelpLink}/guides/add-recurring-event.aspx" can easily be found there.\n\n*#2 Manage your subscriptions*\n\nYou’ll get notified about shared docs, projects updates, and your colleagues birthdays. Switch notifications on and off on your Profile page. Pick those that are useful for you and choose whether you want to get them via email, Chat, or both. You can also unsubscribe from these emails with tips and tricks there or, vice versa, re-enable them. "Learn more >>":"${__HelpLink}/tipstricks/managing-subscriptions.aspx"\n\n*#3 Request special training*\n\nTo get a real quick start with R7-OFFICE, ask us to teach your whole team to use all the modules and features. This is a paid option. "Contact us >>":"mailto:sales@r7-office.ru" \n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_comfort_tips_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nМы работаем для того, чтобы сделать вашу работу с Р7-Офис более комфортной.\n\n*#1 Моментально получайте ответы по функциональности Р7-Офис*\n\nПользуетесь "справочным центром":"${__HelpLink}", если вы не знаете, как решить вашу задачу. В нем легко найти ответы на часто возникающие вопросы, например, "как импортировать контакты в CRM":"${__HelpLink}/guides/import-contacts.aspx" или "как экспортировать данные из CRM":"${__HelpLink}/guides/export-data.aspx", или "как добавить повторяющееся событие":"${__HelpLink}/guides/add-recurring-event.aspx".\n\n*#2 Управляйте уведомлениями*\n\nВы будете получать уведомления об общих документах, обновлениях проектов и днях рождения ваших коллег. Включать и выключить уведомления вы можете на странице вашего профиля. Выберите те, которые вам необходимы, и укажите как вы хотите их получать: по электронной почте, через чат или обоими способами одновременно. Вы в любой момент можете отписаться от уведомлений или, наоборот, включить их. "Узнать больше >>":"${__HelpLink}/tipstricks/managing-subscriptions.aspx"\n\n*#3 Запрашивайте персональное обучение*\n\nДля быстрого старта полноценной работы с Р7-Офис закажите нам обучение вашей команды. Мы покажем вам как наиболее эффективно использовать возможности Р7-Офис. Обучение проводится на платной основе. "Свяжитесь с нами >>":"mailto:sales@r7-office.ru" \n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_comfort_tips_v10';

UPDATE res_data SET textValue='Get R7-OFFICE apps' WHERE fileid=250 AND cultureTitle='Neutral' AND title='subject_saas_admin_user_apps_tips_v10';
UPDATE res_data SET textValue='Скачайте клиентские приложения Р7-Офис для ваших устройств' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_user_apps_tips_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nGet R7-OFFICE apps to work on documents and projects from any of your devices.\n\n# To work on documents offline on Windows, Linux and Mac, download "R7-OFFICE Desktop Editors":"https://r7-office.ru/downloads/".\n# To edit documents on mobile devices, download free R7-OFFICE Documents app for "iOS":"https://apps.apple.com/ru/app/%D1%807-%D0%BE%D1%84%D0%B8%D1%81-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/id1451950062" or "Android":"https://play.google.com/store/apps/details?id=ru.nct.documents&hl=ru".\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_user_apps_tips_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nВы можете скачать клиентские приложения Р7-Офис для работы с документами и проектами для любого из ваших устройств.\n\n# Для работы с документами в автономном режиме в Windows, Linux и Mac загрузите "Р7-Офис Десктоп Редакторы":"https://r7-office.ru/downloads/".\n# Для редактирования документов на мобильных устройствах используется бесплатные приложение Р7-Офис для "iOS":"https://apps.apple.com/ru/app/%D1%807-%D0%BE%D1%84%D0%B8%D1%81-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/id1451950062" или "Android":"https://play.google.com/store/apps/details?id=ru.nct.documents&hl=ru".\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_user_apps_tips_v10';

UPDATE res_data SET textValue='Воспоьзуйтесь скидкой до окончания пробного периода' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_trial_warning_before5_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nThe trial period for your account at "${__VirtualRootPath}":"${__VirtualRootPath}" will be over in 5 days.\n\n*Buy a subscription today with 10% off!*\n\nJust use this coupon code while purchasing: *$Coupon*\n\nAt this moment the number of active users in the portal is $ActiveUsers.\n\n"Write to us to purchase a subscription":"mailto:sales@r7-office.ru"\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_trial_warning_before5_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nПробный период для вашей учетной записи на "${__VirtualRootPath}":"${__VirtualRootPath}" закончится через 5 дней.\n\n*Купить подписку сегодня можно со скидкой 10%!*\n\nНа данный момент количество активных пользователей на вашем портале составляет $ActiveUsers.\n\n"Для приобретения подписки Напишите нам.":"mailto:sales@r7-office.ru"\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_trial_warning_before5_v10';

UPDATE res_data SET textValue='Пробный период вашего Р7-Офис закачивается сегодня' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_trial_warning_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nThe trial period for your portal at "${__VirtualRootPath}":"${__VirtualRootPath}" is due to expire today. To continue using it, "write us to buy subscription":"mailto:sales@r7-office.ru".\n\n*Note*: you can deploy R7-OFFICE on your private network to get full control over your data. "Learn more":"https://helpcenter.r7-office.ru/server/enterprise.aspx"\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_trial_warning_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nПробный период для вашего портала "${__VirtualRootPath}":"${__VirtualRootPath}" истекает сегодня. Чтобы продолжить использовать Р7-Офис, "напишите нам для приобреститения подписки":"mailto:sales@r7-office.ru".\n\n*Примечание*: вы можете развернуть Р7-Офис в своей локальной сети, чтобы получить полный контроль над вашими данными. "Узнать больше":"https://helpcenter.r7-office.ru/server/enterprise.aspx"\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_trial_warning_v10';

UPDATE res_data SET textValue='Hello, $UserName!\n\nDidn’t manage to have a closer look at R7-OFFICE? Extend your trial today! Even more - pay less if your decision is quick and positive! \n\nGet 20 additional days of the trial or a 20% discount on 1 or 3-year subscription. You will be able to use the discount within 5 days after receiving this message.\n\n"Send Request":"mailto:sales@r7-office.ru"\n\nYou can also deploy R7-OFFICE on your private network to get full control over your data. "Learn more":"https://helpcenter.r7-office.ru/server/enterprise.aspx"\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_trial_warning_after5_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nНе удалось подробно познакомиться с Р7-Офис? Продлите пробную версию сегодня! Или сэкономьте, приняв решение о покупке!\n\nПолучите 20 дополнительных дней пробной версии или скидку 20% на подписку на 1 или 3 года. Вы сможете воспользоваться скидкой в течение 5 дней после получения этого сообщения.\n\n"Послать запрос":"mailto:sales@r7-office.ru"\n\nВы также можете развернуть Р7-Офис в вашей локальной сети, чтобы получить полный контроль над вашими данными. "Узнать больше":"https://helpcenter.r7-office.ru/server/enterprise.aspx"\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_trial_warning_after5_v10';

UPDATE res_data SET textValue='Переходите бесплатно на Р7-Офис Персональное облако' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_trial_warning_after30_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nYou haven’t added any teammates, so maybe "R7-OFFICE Personal":"https://test-cloud.r7-office.ru/" suits you more? It is free and you will be able to:\n\n# Work with text documents, spreadsheets, and presentations.\n# Share docs with your friends and collaborate on them in real-time.\n# Embed documents to your web page.\n# Connect 3rd party cloud storage like Yandex.Disk, Dropbox or Google Drive to manage docs from one place.\n\nTo get a quick start, sign up via your Mail.ru, Yandex, Facebook or Google account.\n\n"Start now":"https://test-cloud.r7-office.ru/"\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_trial_warning_after30_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nВы не пригласили никого в ваш облачный офис. Возможно, Вам больше подходит "Р7-Офис Персональное облако":"https://test-cloud.r7-office.ru/"? Это бесплатно. Вы сможете:\n\n# Работать с текстовыми документами, электронными таблицами и презентациями.\n# Делиться документами и совместно работать над ними со своими друзьями в режиме реального времени.\n# Интегрировать документы на вашу веб-страницу.\n# Подключать стороннее облачное хранилище, например Яндекс.Диск, Dropbox или Google Drive, чтобы управлять документами из одного места.\n\nДля быстрого доступа, зарегистрируйтесь через свою учетную запись Mail.ru, Яндекс, Facebook или Google.\n\n"Начать сейчас":"https://test-cloud.r7-office.ru/"\n\nЖелаем приятной работы,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_trial_warning_after30_v10';

UPDATE res_data SET textValue='Специальное предложение на Р7-Офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_payment_after_monthly_subscriptions_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nEarlier you have paid for a monthly subscription. If you are planning to continue using R7-OFFICE, we recommend you purchasing longer subscriptions.\n\nHere’s our special offer - use this coupon *10%discountyear* to get 10% discount on 1-year subscription or this one *upgradethreeyears20%* to buy 3-year subscription with 20% off.\n\nTo continue using R7-OFFICE, write us to buy subscription \n\n"Buy now":"mailto:sales@r7-office.ru"\n\nIf you need assistance, contact us at "support@r7-office.ru":"mailto:support@r7-office.ru". We will be happy to help!\n \nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_payment_after_monthly_subscriptions_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nРанее вы приобрели ежемесячную подписку на Р7-Офис. Если вы планируете продолжать использовать Р7-Офис, мы рекомендуем вам покупать подписки на больший срок.\n\nСпециальное предложение для Вас: купон *10%discountyear*, чтобы получить 10% скидку на годовую подписку, или купон *upgradethreeyears20%*, чтобы купить 3-летнюю подписку со скидкой 20%.\n\nЧтобы продолжить использовать Р7-Офис, напишите нам для продления подписки \n\n"Купить сейчас":"mailto:sales@r7-office.ru"\n\nЕсли вам нужна помощь, свяжитесь с нами по адресу "support@r7-office.ru":"mailto:support@r7-office.ru". Мы будем рады помочь!\n \nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_payment_after_monthly_subscriptions_v10';

UPDATE res_data SET textValue='Продление подписки Р7-Офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_payment_warning_before5_v10';
UPDATE res_data SET textValue='Hello, $UserName!\n\nYour R7-OFFICE subscription is about to expire in 5 days. Renew your R7-OFFICE subscription to continue using it.\n\nTo continue using R7-OFFICE, write us to buy subscription \n\n"Renew now":"mailto:sales@r7-office.ru"\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_payment_warning_before5_v10';
UPDATE res_data SET textValue='Здравствуйте, $UserName!\n\nСрок действия вашей подписки Р7-Офис истекает через 5 дней. Продлите подписку Р7-Офис, чтобы продолжить ее использовать.\n\nЧтобы продолжить использовать Р7-Офис, напишите нам для продления подписки \n\n"Продлить сейчас":"mailto:sales@r7-office.ru"\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_payment_warning_before5_v10';

UPDATE res_data SET textValue='Р7-Офис сообщение о продлении' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_payment_warning_after1_v10';
UPDATE res_data SET textValue='Your R7-OFFICE subscription has expired. Renew your R7-OFFICE subscription to continue using it.\n\nTo continue using R7-OFFICE, write us to buy subscription \n\n"Renew now":"mailto:sales@r7-office.ru"\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_payment_warning_after1_v10';
UPDATE res_data SET textValue='Ваша подписка на Р7-Офис истекла. Продлите подписку Р7-Офис для продолжения использования.\n\nЧтобы продолжить использовать Р7-Офис, напишите нам для продления подписки\n\n"Продлить сейчас":"mailto:sales@r7-office.ru"\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_payment_warning_after1_v10';

UPDATE res_data SET textValue='Удаление вашего портала Р7-Офис' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_saas_admin_trial_warning_after_half_year_v10';
UPDATE res_data SET textValue='You haven’t entered your R7-OFFICE "${__VirtualRootPath}":"${__VirtualRootPath}" for more than half a year. Since you have decided not to use it anymore, your web-office and all the data will be deleted in accordance with our Privacy statement.\n\nWe would appreciate your feedback. Why have you decided to stop using R7-OFFICE?\n\n"Leave feedback":"mailto:sales@r7-office.ru"\n\nIf you think this is a mistake and want to continue using R7-OFFICE, please contact our "support team":"https://r7-office.zendesk.com/hc/ru/requests/new".\n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_saas_admin_trial_warning_after_half_year_v10';
UPDATE res_data SET textValue='Вы не входил на ваш портал Р7-Офис "${__VirtualRootPath}":"${__VirtualRootPath}" более полугода. Поскольку вы решили больше не использовать его, ваш облачный офис и все данные будут удалены в соответствии с нашим Заявлением о конфиденциальности.\n\nМы будем благодарны за ваш отзыв. Почему вы решили прекратить использование Р7-Офис?\n\n"Оставьте отзыв":"mailto:sales@r7-office.ru"\n\nЕсли вы считаете, что это ошибка и хотите продолжать использовать Р7-Офис, обратитесь в нашу "службу поддержки":"https://r7-office.zendesk.com/hc/ru/requests/new".\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_saas_admin_trial_warning_after_half_year_v10';

UPDATE res_data SET textValue='Ваш Р7-Офис деактивирован' WHERE fileid=250 AND cultureTitle='ru' AND title='subject_portal_delete_success_v10';
UPDATE res_data SET textValue='Your R7-OFFICE has been successfully deactivated. Please note that all of your data will be deleted in accordance with our Privacy statement. \n\nWhy have you decided to leave? Share your experience with us.\n\n"Leave feedback":"mailto:sales@r7-office.ru"\n\nThank you and good luck! \n\nTruly yours,\nR7-OFFICE Team\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='Neutral' AND title='pattern_portal_delete_success_v10';
UPDATE res_data SET textValue='Ваш Р7-Офис был успешно деактивирован. Обратите внимание, что все ваши данные будут удалены в соответствии с нашим Заявлением о конфиденциальности.\n\nПочему вы решили уйти? Поделитесь с нами своим опытом.\n\n"Оставьте отзыв":"mailto:sales@r7-office.ru"\n\nСпасибо за сотрудничество, удачи!\n\nИскренне ваша,\nКоманда Р7-Офис\n"www.r7-office.ru":"http://r7-office.ru/"' WHERE fileid=250 AND cultureTitle='ru' AND title='pattern_portal_delete_success_v10';
