---
- hosts: mysql
  gather_facts: True
  become: True
  roles:
    - deploy_mysql

- hosts: master_db
  gather_facts: True
  become: True
  roles:
    - mysql_master

- hosts: slave_db
  gather_facts: True
  become: True
  tasks:
    - name: slave role
      include_role:
        name: mysql_slave
      when: mysql_cluster == "true"

- hosts: ds
  gather_facts: True
  become: True
  roles:
    - deploy_DS

- hosts: cs
  gather_facts: True
  become: True
  roles:
    - deploy_CS

- hosts: nginx
  gather_facts: True
  become: True
  roles:
    - deploy_nginx