---
- name: Copy elasticsearch.yml
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0744'
  notify: Restart elasticsearch

- name: Copy jvm.options.j2
  ansible.builtin.template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: '0744'
  notify: Restart elasticsearch

- name: Download plugin
  get_url:
    url: "{{ url_attach_elas }}"
    dest: /tmp/ingest-attachment.zip
    mode: '0644'
    validate_certs: no
    force: yes

- name: Install ingest-attachment
  ansible.builtin.shell:
    cmd: yes | /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///tmp/ingest-attachment.zip
  notify: Restart elasticsearch
