---
- name: сopy install-AstraLinux.sh
  ansible.builtin.template:
    src: scripts/install-AstraLinux.sh.j2
    dest: /tmp/install-AstraLinux.sh
    owner: root
    group: root
    mode: '0644'

- name: сopy install-app.sh
  ansible.builtin.template:
    src: scripts/install-AstraLinux/install-app.sh.j2
    dest: /tmp/install-app.sh
    owner: root
    group: root
    mode: '0644'

- name: сopy install-preq.sh
  ansible.builtin.template:
    src: scripts/install-AstraLinux/install-preq.sh.j2
    dest: /tmp/install-preq.sh
    owner: root
    group: root
    mode: '0644'

- name: update all packages
  apt:
    name: "*"
    update_cache: yes
    state: latest

- name: pre-installation
  apt:
    name: "{{ packagesDeb }}"

- name: run get-pip.py
  ansible.builtin.shell:
    cmd: curl -fsSL https://bootstrap.pypa.io/pip/3.5/get-pip.py | python3.5
  when: ansible_facts['distribution_version'] == "16.04"

- name: run a script
  ansible.builtin.shell:
    cmd: bash /tmp/install-AstraLinux.sh
  register: runscript

- name: debug runscript
  debug:
    msg: "{{ runscript.stdout_lines }}"